In [1]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.append('..')
from typing import Dict, List
import torch
from pathlib import Path
import pandas as pd
import numpy as np
from viz.plot import plot_matrix_G, plot_matrix_F, plot_aggregation_weights, plot_matrix_G_condition_number, plot_inverse_matrix_G
from approaches.aggregation import Aggregator
import matplotlib.pyplot as plt
from misc.analyses import aggregation_rcond_sweep, aggregation_num_svd_sweep, aggregation_rcond_sweep_per_dataset

# 'rcond' sweeps

The following tables show the mean accuracy of IWA (Aggregation method) for different rcond parameters for inversion of the matrix G (similarity matrix).
The printed tables are the means over seeds and different domain adaption tasks.

In [2]:
dataset_tables = {}
def name_mapping(name):
    if name in ['dann', 'cmd', 'mmd']:
        return name.upper()
    elif name == 'HHAR_SA':
        return 'HHAR'
    elif name == 'HAR':
        return 'UCI-HAR'
    elif name == 'EEG':
        return 'Sleep-EDF'
    elif name == 'MINI_DOMAIN_NET':
        return 'MiniDomainNet'
    elif name == 'AMAZON_REVIEWS':
        return 'Amazon Reviews'
    elif name == 'MOONS':
        return 'Transformed Moons'
    else:
        return name

### AdaTime - HHAR-SA

In [3]:
res_dir = 'results/ADATIME/HHAR_SA'
from extractor.adatime_hhar_sa_results_loader import ResultsLoader
seeds = [1,2,3]
rconds: List[float] = [1.0, 0.5, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7]
res_df_at_hharsa = aggregation_rcond_sweep_per_dataset(
    results_dir=res_dir, seeds=seeds, results_loader_class=ResultsLoader, rconds=rconds)
dataset_tables[name_mapping(Path(res_dir).stem)] = res_df_at_hharsa

Aggregation for HoMM
Aggregation for AdvSKM
Aggregation for DIRT
Aggregation for DDC
Aggregation for MMDA
Aggregation for CoDATS
Aggregation for Deep_Coral
Aggregation for CDAN
Aggregation for DANN
Aggregation for DSAN

In [4]:
display_df = res_df_at_hharsa.groupby(['Method', 'domain']).mean()
print('Adatime - HHAR-SA')
display(display_df.style.highlight_max(color='green', axis=1))
display_df = res_df_at_hharsa.groupby(['domain']).mean()
display(display_df.style.highlight_max(color='green', axis=1))

Adatime - HHAR-SA

### AdaTime - EEG

In [5]:
res_dir = 'results/ADATIME/EEG'
from extractor.adatime_eeg_results_loader import ResultsLoader
seeds = [1,2,3]
rconds: List[float] = [1.0, 0.5, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7]
res_df_at_eeg = aggregation_rcond_sweep_per_dataset(
    results_dir=res_dir, seeds=seeds, results_loader_class=ResultsLoader, rconds=rconds)
dataset_tables[name_mapping(Path(res_dir).stem)] = res_df_at_eeg

Aggregation for HoMM
Aggregation for AdvSKM
Aggregation for DIRT
Aggregation for DDC
Aggregation for MMDA
Aggregation for CoDATS
Aggregation for Deep_Coral
Aggregation for CDAN
Aggregation for DANN
Aggregation for DSAN

In [6]:
display_df = res_df_at_eeg.groupby(['Method', 'domain']).mean()
print('Adatime - EEG')
display(display_df.style.highlight_max(color='green', axis=1))
display_df = res_df_at_eeg.groupby(['domain']).mean()
display(display_df.style.highlight_max(color='green', axis=1))

Adatime - EEG

### AdaTime - HAR

In [8]:
res_dir = 'results/ADATIME/HAR'
from extractor.adatime_har_results_loader import ResultsLoader
seeds = [1,2,3]
rconds: List[float] = [1.0, 0.5, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7]
res_df_at_har = aggregation_rcond_sweep_per_dataset(
    results_dir=res_dir, seeds=seeds, results_loader_class=ResultsLoader, rconds=rconds)
dataset_tables[name_mapping(Path(res_dir).stem)] = res_df_at_har

Aggregation for HoMM
Aggregation for AdvSKM
Aggregation for DIRT
Aggregation for DDC
Aggregation for MMDA
Aggregation for CoDATS
Aggregation for Deep_Coral
Aggregation for CDAN
Aggregation for DANN
Aggregation for DSAN

In [9]:
display_df = res_df_at_eeg.groupby(['Method', 'domain']).mean()
print('Adatime - HAR')
display(display_df.style.highlight_max(color='green', axis=1))
display_df = res_df_at_eeg.groupby(['domain']).mean()
display(display_df.style.highlight_max(color='green', axis=1))

Adatime - HAR

### AdaTime - WISDM

In [10]:
res_dir = 'results/ADATIME/WISDM'
from extractor.adatime_wisdm_results_loader import ResultsLoader
seeds = [1,2,3]
rconds: List[float] = [1.0, 0.5, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7]
res_df_at_wisdm = aggregation_rcond_sweep_per_dataset(
    results_dir=res_dir, seeds=seeds, results_loader_class=ResultsLoader, rconds=rconds)
dataset_tables[name_mapping(Path(res_dir).stem)] = res_df_at_wisdm

Aggregation for HoMM
Aggregation for AdvSKM
Aggregation for DIRT
Aggregation for DDC
Aggregation for MMDA
Aggregation for CoDATS
Aggregation for Deep_Coral
Aggregation for CDAN
Aggregation for DANN
Aggregation for DSAN

In [11]:
display_df = res_df_at_eeg.groupby(['Method', 'domain']).mean()
print('Adatime - WISDM')
display(display_df.style.highlight_max(color='green', axis=1))
display_df = res_df_at_eeg.groupby(['domain']).mean()
display(display_df.style.highlight_max(color='green', axis=1))

Adatime - WISDM

### MOONS

In [12]:
res_dir = 'results/BP/MOONS/'
from extractor.twinmoons_results_loader import ResultsLoader
seeds = [1,2,3,4,5]
rconds: List[float] = [1.0, 0.5, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7]
res_df_tm = aggregation_rcond_sweep_per_dataset(
    results_dir=res_dir, seeds=seeds, results_loader_class=ResultsLoader, rconds=rconds)
dataset_tables[name_mapping(Path(res_dir).stem)] = res_df_tm

Aggregation for cmd
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 15 due to NaN predictions..
Aggregation for mmd
Aggregation for dann

In [13]:
display_df = res_df_tm.groupby(['Method', 'domain']).mean()
print('MOONS')
display(display_df.style.highlight_max(color='green', axis=1))
display_df = res_df_tm.groupby(['domain']).mean()
display(display_df.style.highlight_max(color='green', axis=1))

MOONS

### Mini-DomainNet

In [14]:
res_dir = 'results/BP/MINI_DOMAIN_NET/'
from extractor.minidomainnet_results_loader import ResultsLoader
seeds = [11223, 213564, 844585]
rconds: List[float] = [1.0, 0.5, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7]
res_df_dn = aggregation_rcond_sweep_per_dataset(
    results_dir=res_dir, seeds=seeds, results_loader_class=ResultsLoader, rconds=rconds)
dataset_tables[name_mapping(Path(res_dir).stem)] = res_df_dn

Aggregation for cmd
Aggregation for mmd
Aggregation for dann

In [15]:
display_df = res_df_dn.groupby(['Method', 'domain']).mean()
print('Mini-DomainNet')
display(display_df.style.highlight_max(color='green', axis=1))
display_df = res_df_dn.groupby(['domain']).mean()
display(display_df.style.highlight_max(color='green', axis=1))

Mini-DomainNet

### Amazon Reviews

In [22]:
res_dir = 'results/BP/AMAZON_REVIEWS/'
from extractor.amazon_results_loader import ResultsLoader
seeds = [1,2,3,4,5]
rconds: List[float] = [1.0, 0.5, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7]
res_df_ar = aggregation_rcond_sweep_per_dataset(
    results_dir=res_dir, seeds=seeds, results_loader_class=ResultsLoader, rconds=rconds)
dataset_tables[name_mapping(Path(res_dir).stem)] = res_df_ar

Aggregation for cmd
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..
Skipping lambda 10 due to NaN predictions..
Skipping lambda 1.5 due to NaN predictions..
Skipping lambda 2 due to NaN predictions..
Skipping lambda 5 due to NaN predictions..

In [23]:
display_df = res_df_ar.groupby(['Method', 'domain']).mean()
print('Amazon Reviews')
display(display_df.style.highlight_max(color='green', axis=1))
display_df = res_df_dn.groupby(['domain']).mean()
display(display_df.style.highlight_max(color='green', axis=1))

Amazon Reviews

## Combined table for all datasets

In [24]:
combined_table = pd.concat(dataset_tables, names=['Dataset'])

In [25]:
display_df = combined_table.groupby(['Dataset','domain']).mean()
display(display_df.style.highlight_max(color='green', axis=1))

In [54]:
display_df = combined_table.copy()
display(display_df.style.highlight_max(color='green', axis=1))

In [48]:
df = combined_table.copy()

In [52]:
source_results = df.xs('source', level='domain', drop_level=False)
target_results = df.xs('source', level='domain', drop_level=False)

In [55]:

for (s_idx, s_row), (t_idx, t_row) in zip(source_results.iterrows(), target_results.iterrows()):
    print(s_idx)
    print(s_row)
    # get idxes with maximum accuracy on source 
    # check if max on target is same for

('HHAR', 'HoMM', '0_src-6_tgt', 1, 'source')
1.000000e+00    0.209821
5.000000e-01    0.982143
1.000000e-01    0.982143
1.000000e-02    0.982143
1.000000e-03    0.982143
1.000000e-04    0.982143
1.000000e-05    0.982143
1.000000e-06    0.982143
1.000000e-07    0.982143
Name: (HHAR, HoMM, 0_src-6_tgt, 1, source), dtype: float64

In [36]:
print(combined_table.idxmax(axis=1).to_string())

Dataset            Method      Task                                              seed    domain
HHAR               HoMM        0_src-6_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 3       source    5.000000e-01
                                                                                         target    5.000000e-01
                               1_src-6_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    1.000000e-02
                                                                                         target    1.000000e-02
                                                                                 3       source    5.000000e-01
                                                                                         target    5.000000e-01
                               2_src-7_tgt                                       1       source    5.000000e-01
                                                                                         target    1.000000e-02
                                                                                 2       source    5.000000e-01
                                                                                         target    1.000000e-03
                                                                                 3       source    5.000000e-01
                                                                                         target    1.000000e-02
                               3_src-8_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 3       source    5.000000e-01
                                                                                         target    5.000000e-01
                               4_src-5_tgt                                       1       source    5.000000e-01
                                                                                         target    1.000000e-02
                                                                                 2       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 3       source    1.000000e-02
                                                                                         target    5.000000e-01
                   AdvSKM      0_src-6_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 3       source    5.000000e-01
                                                                                         target    1.000000e-02
                               1_src-6_tgt                                       1       source    1.000000e-04
                                                                                         target    5.000000e-01
                                                                                 2       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 3       source    1.000000e-02
                                                                                         target    5.000000e-01
                               2_src-7_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    1.000000e-03
                                                                                         target    1.000000e-02
                                                                                 3       source    5.000000e-01
                                                                                         target    1.000000e-03
                               3_src-8_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 3       source    5.000000e-01
                                                                                         target    5.000000e-01
                               4_src-5_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    1.000000e-04
                                                                                         target    5.000000e-01
                                                                                 3       source    5.000000e-01
                                                                                         target    1.000000e-02
                   DIRT        0_src-6_tgt                                       1       source    1.000000e-02
                                                                                         target    1.000000e-02
                                                                                 2       source    1.000000e-01
                                                                                         target    1.000000e-02
                                                                                 3       source    5.000000e-01
                                                                                         target    1.000000e-03
                               1_src-6_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    1.000000e-05
                                                                                         target    5.000000e-01
                                                                                 3       source    5.000000e-01
                                                                                         target    5.000000e-01
                               2_src-7_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 3       source    5.000000e-01
                                                                                         target    5.000000e-01
                               3_src-8_tgt                                       1       source    1.000000e-04
                                                                                         target    1.000000e-02
                                                                                 2       source    5.000000e-01
                                                                                         target    1.000000e-02
                                                                                 3       source    5.000000e-01
                                                                                         target    5.000000e-01
                               4_src-5_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    1.000000e-02
                                                                                         target    5.000000e-01
                                                                                 3       source    5.000000e-01
                                                                                         target    5.000000e-01
                   DDC         0_src-6_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    1.000000e-02
                                                                                         target    5.000000e-01
                                                                                 3       source    5.000000e-01
                                                                                         target    5.000000e-01
                               1_src-6_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    1.000000e-02
                                                                                         target    5.000000e-01
                                                                                 3       source    5.000000e-01
                                                                                         target    5.000000e-01
                               2_src-7_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    5.000000e-01
                                                                                         target    1.000000e-03
                                                                                 3       source    5.000000e-01
                                                                                         target    1.000000e-03
                               3_src-8_tgt                                       1       source    5.000000e-01
                                                                                         target    1.000000e-02
                                                                                 2       source    1.000000e-02
                                                                                         target    5.000000e-01
                                                                                 3       source    1.000000e-02
                                                                                         target    5.000000e-01
                               4_src-5_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 3       source    5.000000e-01
                                                                                         target    1.000000e-02
                   MMDA        0_src-6_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 3       source    5.000000e-01
                                                                                         target    5.000000e-01
                               1_src-6_tgt                                       1       source    5.000000e-01
                                                                                         target    1.000000e-02
                                                                                 2       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 3       source    5.000000e-01
                                                                                         target    5.000000e-01
                               2_src-7_tgt                                       1       source    1.000000e-02
                                                                                         target    1.000000e-02
                                                                                 2       source    1.000000e-03
                                                                                         target    5.000000e-01
                                                                                 3       source    5.000000e-01
                                                                                         target    1.000000e-03
                               3_src-8_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    5.000000e-01
                                                                                         target    1.000000e-02
                                                                                 3       source    5.000000e-01
                                                                                         target    5.000000e-01
                               4_src-5_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    1.000000e-03
                                                                                         target    5.000000e-01
                                                                                 3       source    5.000000e-01
                                                                                         target    5.000000e-01
                   CoDATS      0_src-6_tgt                                       1       source    1.000000e-03
                                                                                         target    1.000000e-02
                                                                                 2       source    1.000000e-02
                                                                                         target    1.000000e-02
                                                                                 3       source    1.000000e-01
                                                                                         target    1.000000e-03
                               1_src-6_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    1.000000e-03
                                                                                         target    5.000000e-01
                                                                                 3       source    1.000000e-03
                                                                                         target    5.000000e-01
                               2_src-7_tgt                                       1       source    5.000000e-01
                                                                                         target    1.000000e-03
                                                                                 2       source    5.000000e-01
                                                                                         target    1.000000e-03
                                                                                 3       source    5.000000e-01
                                                                                         target    1.000000e-03
                               3_src-8_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 3       source    5.000000e-01
                                                                                         target    5.000000e-01
                               4_src-5_tgt                                       1       source    5.000000e-01
                                                                                         target    5.000000e-01
                                                                                 2       source    1.000000e-02

In [60]:
best_rcond = combined_table.groupby(['Dataset', 'Method', 'Task', 'domain']).mean().idxmax(axis=1)

In [61]:
best_rcond_src_tgt = (best_rcond.xs('source', level='domain') == best_rcond.xs('target', level='domain'))

In [62]:
best_rcond_src_tgt.value_counts()

True     168
False     89
dtype: int64

In [56]:
551 / 849

0.6489988221436984